# Generated by Django 6.0.1 on 2026-03-23 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('description', models.TextField(max_length=200)),
                ('location', models.ManyToManyField(blank=True, related_name='loc_stores', to='location_app.location')),
            ],
        ),
    ]
