# Generated by Django 6.0.1 on 2026-03-23 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('category', models.CharField(choices=[(None, 'Unknown'), ('Fresh produce and herbs', 'Fresh'), ('Salty snacks', 'Salty'), ('Sweet snacks', 'Sweet'), ('Eggs or dairy', 'Animal'), ('Meat, chicken, seafood', 'Meat'), ('Breads or baked goods', 'Bread'), ('Dried goods', 'Dried'), ('Canned goods', 'Canned'), ('Dried seasonings', 'Seasoning'), ('Other', 'Other')], default='Other')),
                ('description', models.TextField(max_length=200)),
            ],
        ),
    ]
