# Generated by Django 6.0.1 on 2026-03-23 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food_app', '0001_initial'),
        ('stores_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='stores',
            field=models.ManyToManyField(blank=True, related_name='store_foods', to='stores_app.store'),
        ),
    ]
