# Generated by Django 6.0.1 on 2026-03-24 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[(None, 'Unknown'), ('FRESH', 'Fresh produce and herbs like fruits and vegetables'), ('SALTY', 'Salty snacks like chips'), ('SWEET', 'Sweet snacks like packaged cookies'), ('EGGS', 'Egg products'), ('DAIRY', 'Dairy products like milk, butter, yogurt, etc.'), ('MEAT', 'Red meat like beef or veal'), ('PORK', 'Pig meat products like pork chop, sausage, ham hocks'), ('CHICKEN', 'Chicken products like whole chicken, breast, etc, not from frozen'), ('SEAFOOD', 'Seafood products like fish, crab, etc.'), ('BREAD', 'Bread products e.g. tost style, loaf, baguette'), ('BAKED_GOODS', 'Baked goods like pies, pastries, muffins, cakes'), ('DRIED', 'Dried food goods like beans, rice, bulgur'), ('CANNED', 'Canned food goods like canned beans, meats, fish'), ('SEASONING', 'Dried seasonings like salt, paprika, kekik'), ('FROZEN', 'Frozen goods like frozen pizza, chicken tenders'), ('Other', "use this category for items that don't fit correctly in one category")], default='Other'),
        ),
    ]
